name: Build and Release Binaries (Linux Only)

on:
  release:
    types: [published]

permissions:
  contents: write # Grant write access to repository contents for all jobs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20'

      - name: Build Binary (Linux)
        run: |
          go build -ldflags="-s -w" -o ${{ github.event.repository.name }}-linux .

      - name: Upload Binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.repository.name }}-linux

# No second "release" job needed anymore — softprops/action-gh-release uploads directly to the current release!

