name: Build and Release Binaries (Linux Only)

on:
  release:
    types: [published]

permissions:
  contents: write      # Grant write access to repository contents
  id-token: write      # Needed to upload release assets with GitHub Token

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.20'

      - name: Build Binary (no suffix)
        run: |
          go build -ldflags="-s -w" -o dns-checker .

      - name: Upload Binary to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dns-checker
          asset_name: dns-checker
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is passed explicitly

